### ISSUE TITLE
Reconnecting data object to text annotation breaks modeler

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1008]
__Describe the Bug__

Diagram breaks when trying to reconnect data association to text annotation.

![data-output-1](https://user-images.githubusercontent.com/28307541/56960271-88e86c80-6b50-11e9-9df3-403ef1bbac29.gif)

See the attached logs for the error.

__Steps to Reproduce__

1. Create a task.
2. Add text annotation.
3. Create a data object.
4. Connect data object to the task.
5. Try to reconnect data association to text annotation.

After that, the shapes will never be rerendered after movement.

__Expected Behavior__

Connection should be disallowed and the diagram should be still editable.

__Environment__

Please complete the following information:

 - Browser: Chrome 73 (for demo.bpmn.io)
 - OS: MacOS
 - Library version: bpmn-js@3.4.0 and Camunda Modeler 3.0.1

__Logs__

<details><summary>Click to open log</summary>

```
[2019-04-30T11:52:02.659Z] client:error [diagram_4.bpmn] Cannot read property 'push' of undefined
    at push (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:603:0)
    at updateSemanticParent (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:679:0)
    at updateConnection (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:171:0)
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/6.6.js:1:481809
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/0.0.js:1:214623
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:362:0)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:348:0)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:310:0)
    at fire (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:346:0)
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/0.0.js:1:318674
[2019-04-30T11:52:02.994Z] client:error [diagram_4.bpmn] Cannot read property 'push' of undefined
    at push (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:603:0)
    at updateSemanticParent (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:679:0)
    at updateConnection (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:171:0)
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/6.6.js:1:481809
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/0.0.js:1:214623
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:362:0)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:348:0)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:310:0)
    at fire (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:346:0)
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/0.0.js:1:318674
[2019-04-30T11:52:04.438Z] client:error [diagram_4.bpmn] Cannot read property 'push' of undefined
    at push (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:603:0)
    at updateSemanticParent (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:679:0)
    at updateConnection (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:171:0)
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/6.6.js:1:481809
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/0.0.js:1:214623
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:362:0)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:348:0)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:310:0)
    at fire (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:346:0)
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/0.0.js:1:318674
[2019-04-30T11:52:04.759Z] client:error [diagram_4.bpmn] Cannot read property 'push' of undefined
    at push (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:603:0)
    at updateSemanticParent (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:679:0)
    at updateConnection (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:171:0)
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/6.6.js:1:481809
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/0.0.js:1:214623
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:362:0)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:348:0)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:310:0)
    at fire (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:346:0)
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/0.0.js:1:318674
[2019-04-30T11:52:05.114Z] client:error [diagram_4.bpmn] Cannot read property 'push' of undefined
    at push (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:603:0)
    at updateSemanticParent (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:679:0)
    at updateConnection (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:171:0)
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/6.6.js:1:481809
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/0.0.js:1:214623
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:362:0)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:348:0)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:310:0)
    at fire (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:346:0)
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/0.0.js:1:318674
[2019-04-30T11:52:05.430Z] client:error [diagram_4.bpmn] Cannot read property 'push' of undefined
    at push (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:603:0)
    at updateSemanticParent (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:679:0)
    at updateConnection (webpack:///node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:171:0)
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/6.6.js:1:481809
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/0.0.js:1:214623
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:362:0)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:348:0)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:310:0)
    at fire (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:346:0)
    at file:///Applications/Camunda%20Modeler%203.0.1.app/Contents/Resources/app.asar/public/0.0.js:1:318674
[2019-04-30T11:52:06.938Z] app:workspace saving
[2019-04-30T11:52:06.938Z] app:config set workspace
[2019-04-30T11:52:06.939Z] app:config saved
```
</details>

**Comment by pinussilvestrus** [comment]
I can reproduce this. It is correct, that this shouldn't be allowed. Cf. the [BPMN 2.0 reference](https://www.omg.org/spec/BPMN/2.0/About-BPMN/), Data Objects should only be attachable to FlowElements:

![image](https://user-images.githubusercontent.com/9433996/57065379-81989e80-6cc9-11e9-96c2-a0029312f334.png)

We should consider adding a [Rule](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/rules/BpmnRules.js) which disallow adding data associations to Artifacts (which are not FlowElements).

**Comment by barmac** [comment]
Fixed via https://github.com/bpmn-io/bpmn-js/pull/1067

I'll add a test case to prevent it from reocurring.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/pull/1071.
