### ISSUE TITLE
Unparsable Error <bpmn:process> detected while opening with Modeller 

### ISSUE THREAD

**Issue by ramanandh** [bpmn-io/bpmn-js#1495]
Hello

I am building a simple process with Springboot using this video link https://www.youtube.com/watch?v=sgcSm7YneTs&t=253s
and facing issues while opening the process.bpmn in Modeller. 

Any ideas how this can be fixed ??

unparsable content <bpmn:process> detected

[C:\Installs\Camunda Projects\Travel Management\src\main\resources\process.bpmn] no process or collaboration to display
    at Object.handleDefinitions (webpack:///node_modules/bpmn-js/lib/import/BpmnTreeWalker.js:198:14)
    at file:///C:/Installs/camunda-modeler-4.10.0-win-x64/resources/app.asar/public/3.3.js:1:35390
    at file:///C:/Installs/camunda-modeler-4.10.0-win-x64/resources/app.asar/public/3.3.js:1:35413
    at new Promise (<anonymous>)
    at T (webpack:///node_modules/bpmn-js/lib/import/Importer.js:72:9)
    at file:///C:/Installs/camunda-modeler-4.10.0-win-x64/resources/app.asar/public/3.3.js:1:40529
    at new Promise (<anonymous>)
    at S.<anonymous> (webpack:///node_modules/bpmn-js/lib/BaseViewer.js:286:9)
    at apply (webpack:///node_modules/bpmn-js/lib/util/CompatibilityUtil.js:50:17)
    at file:///C:/Installs/camunda-modeler-4.10.0-win-x64/resources/app.asar/public/3.3.js:1:40013
    at new Promise (<anonymous>)
    at S.<anonymous> (webpack:///node_modules/bpmn-js/lib/BaseViewer.js:228:9)
    at apply (webpack:///node_modules/bpmn-js/lib/util/CompatibilityUtil.js:50:17)
    at file:///C:/Installs/camunda-modeler-4.10.0-win-x64/resources/app.asar/public/3.3.js:1:39282 [ error ]
[C:\Installs\Camunda Projects\Travel Management\src\main\resources\process.bpmn] unparsable content <bpmn:process> detected
	line: 2
	column: 2

Cheers
Ram

**Comment by nikku** [comment]
For questions, please turn to out [community forum](https://forum.bpmn.io/).

As the error message indicates there is an issue with your BPMN 2.0 diagram, likely not being valid BPMN 2.0. Sharing it (on the forum) would be helpful for us to look into the issue.
