### ISSUE TITLE
erro on adding pool

### ISSUE THREAD

**Issue by alibahal** [bpmn-io/bpmn-js#1683]
__Describe the Bug__

when adding a pool on latest version ,error generated as follow

__Steps to Reproduce__

1. add pool on empty diagram

cause error :
unhandled error in event listener Error: invalid hit type <no-move>
    at applyStyle (InteractionEvents.js:285:1)
    at InteractionEvents.createBoxHit (InteractionEvents.js:374:1)
    at BpmnInteractionEvents.createParticipantHit (BpmnInteractionEvents.js:72:1)
    at BpmnInteractionEvents.js:34:1
    at invokeFunction (EventBus.js:519:1)
    at EventBus._invokeListener (EventBus.js:371:1)
    at EventBus._invokeListeners (EventBus.js:352:1)
    at EventBus.fire (EventBus.js:313:1)
    at InteractionEvents.js:221:1
    at invokeFunction (EventBus.js:519:1)

EventBus.js:385 
        
       unhandled error in event listener Error: element <Participant_1gxbsx9> already exists
    at Canvas._ensureValid (Canvas.js:812:1)
    at Canvas._addElement (Canvas.js:859:1)
    at Canvas.addShape (Canvas.js:888:1)
    at CreateShapeHandler.execute (CreateShapeHandler.js:54:1)
    at CommandStack.js:415:1
    at CommandStack._atomicDo (CommandStack.js:377:1)
    at CommandStack._internalExecute (CommandStack.js:408:1)
    at CommandStack.execute (CommandStack.js:153:1)
    at Modeling.createShape (Modeling.js:291:1)
    at CreateElementsHandler.js:109:1

__Environment__

 - Browser: [Microsoft Edge Version 102.0.1245.33 (Official build) (64-bit)]
 - OS: [e.g. Windows 11]
  "dependencies": {
    "@babel/core": "^7.17.8",
    "@bpmn-io/properties-panel": "^0.11.0",
    "bpmn-js": "^9.2.2",
    "bpmn-js-embedded-comments": "^0.6.1",
    "bpmn-js-properties-panel": "^1.0.0-alpha.13",
    "diagram-js": "^8.2.1",
    "diagram-js-minimap": "^2.1.1",
    "inherits": "^2.0.4",
    "jquery": "^3.5.1",
    "min-dash": "^3.7.0",
    "tiny-svg": "^2.2.3"
  }

**Comment by alibahal** [comment]
I found the problem. I updated diagram.js to latest version( 8.5.0") and problem solved
