### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'isGeneric')

### ISSUE THREAD

**Issue by liuxsen** [bpmn-io/bpmn-js#1736]
__Describe the Bug__

index.esm.js:1107 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isGeneric')
    at ElementSerializer.build (index.esm.js:1107:37)
    at eval (index.esm.js:1334:30)
    at forEach (index.esm.js:198:16)
    at eval (index.esm.js:1323:56)
    at forEach (index.esm.js:198:16)
    at ElementSerializer.parseContainments (index.esm.js:1299:52)
    at ElementSerializer.build (index.esm.js:1127:10)
    at eval (index.esm.js:1334:30)
    at forEach (index.esm.js:198:16)
    at eval (index.esm.js:1323:56)

![image](https://user-images.githubusercontent.com/12598696/188423634-b8b325e6-2d55-4d18-ad9d-1b86bfa4cc5d.png)

__Steps to Reproduce__

1.

```js
export const typeList = [
  {
    code: 'create.yizhui',
    name: '发送一追话术',
    className: 'yizhui',
    group: 'activity',
    documentation: 'documentation',
    elementPropertyList: [
      {
        $type: 'camunda:Property',
        name: '123',
        value: '123'
        // id: 'task-id',
        // eventType: 'create',
        // listenType: 'class',
        // serviceName: 'java-class-name'
      }
    ],
    extensionElements: {
      values: [
        // {"$type":"camunda:TaskListener",
        // "class":"Java-class",
        // "event":"create",
        // "id":"监听器111",
        // "fields":[{"$type":"camunda:Field","name":"13","string":"123"}],
        // "listenerType":"classListener"
      // }
        // {
        //   $type: 'camunda:ExecutionListener'
        // }
      ]
    }
  }
]

```

2. 
```js
import { typeList } from './constant'

function createTask (bpmnFactory, elementFactory, create, {
  code, name, elementPropertyList, extensionElements, documentation
}) {
  return function (event) {
    const businessObject = bpmnFactory.create('bpmn:ServiceTask')
    businessObject.suitable = 500
    businessObject.documentation = [
      { text: 'text' }
    ]

    const shape = elementFactory.createShape({
      type: 'bpmn:ServiceTask',
      businessObject
    }
    )
    create.start(event, shape)
  }
}

class CustomPalette {
  constructor (bpmnFactory, create, elementFactory, palette, translate) {
    this.bpmnFactory = bpmnFactory
    this.create = create
    this.elementFactory = elementFactory
    this.translate = translate

    palette.registerProvider(this)
  }

  // group： 定义这个shape属于哪个组，主要有tools、event、gateway和activity可以选择
  // className： 定义这个shape的chass名称，可以通过这个class给shape指定具体的样式
  // title： 定义这个shape的title，也就是鼠标移动到shape上的提示
  // action： 用户操作时触发的事件

  getPaletteEntries (element) {
    return typeList.reduce((pre, next) => {
      return {
        ...pre,
        [next.code]: {
          className: next.className,
          title: this.translate(next.name),
          group: next.group,
          action: {
            dragstart: createTask(this.bpmnFactory, this.elementFactory, this.create, { ...next }),
            click: createTask(this.bpmnFactory, this.elementFactory, this.create, { ...next })
          }
        }
      }
    }, {})
  }
}

CustomPalette.$inject = [
  'bpmnFactory',
  'create',
  'elementFactory',
  'palette',
  'translate'
]

export default {
  __init__: ['customPalette'],
  customPalette: ['type', CustomPalette]
}

```

**Comment by pinussilvestrus** [comment]
Can you please share your extension [inside a CodeSandbox](https://codesandbox.io/s/late-flower-eh54kr)? Without it will be hard for us to inspect your reported issue. 

Thank you ❤️
