### ISSUE TITLE
Setting color fails on non-existing `bpmndi:label`

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1791]
__Describe the Bug__

Without a `bpmndi:label` (still a valid BPMN 2.0 diagram) setting colors on an element fails:

```
UpdateModdlePropertiesHandler.js:25 Uncaught Error: <moddleElement> required
    at Vv.execute (UpdateModdlePropertiesHandler.js:25:11)
    at CommandStack.js:411:31
    at Rm._atomicDo (CommandStack.js:375:5)
    at Rm._internalExecute (CommandStack.js:404:8)
    at Rm.execute (CommandStack.js:153:8)
    at SetColorHandler.js:78:26
```

__Steps to Reproduce__

1. Open [`diagram.no-bpmndi-label.bpmn`](https://github.com/bpmn-io/bpmn-js/files/10195838/diagram.no-bpmndi-label.bpmn.txt) on [demo.bpmn.io](https://demo.bpmn.io/).
2. Apply color to external label
3. __See stuff blow up with error message__

__Expected Behavior__

I can set color on the element; if label element is required to set (persist) it, then it shall be created in the process. If we create it (potentially without bounds?) we'd need to make sure it still renders though, on re-import.

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: v11.0.0

**Comment by barmac** [comment]
I can reproduce this. 
I believe the editor should not fail when one tries to color a label even if it does not have DI. The problem lies within https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/cmd/SetColorHandler.js#L78 

As a side note, BPMNLabel is necessary in order to render an element's label:
> Simply put, label visibility is defined by the presence of the BPMNLabel element.
(https://www.omg.org/spec/BPMN/2.0/PDF#page=411)
However, it makes sense to render the labels even if BPMNLabel is missing and add the missing BPMNLabel on element's change.
