### ISSUE TITLE
Aligning Text Annotation with a Sequence flow with name, creates unhandled error in event listener

### ISSUE THREAD

**Issue by par-shd** [bpmn-io/bpmn-js#2239]
### Describe the Bug

An unhandled error in event listener happens when a Text Annotation is getting aligned with a Sequence flow that has a name
<img width="646" alt="image" src="https://github.com/user-attachments/assets/14c588c4-c1a2-4b23-b745-1f1bc53dc9bd">

### Steps to Reproduce

1. Add a Sequence flow and add a name to it
2. Create an annotation for the flow
3. Now, try to align them in a vertical order (You need to release the mouse when the items are aligned)
<img width="250" alt="image" src="https://github.com/user-attachments/assets/3562e6f1-b516-47b1-88b5-575945c4efee">

4. The following error happens:
```
unhandled error in event listener TypeError: Failed to execute 'setTranslate' on 'SVGTransform': The provided float value is non-finite.
    at ro (SvgTransformUtil.js:35:13)
    at io.update (GraphicsFactory.js:277:5)
    at ChangeSupport.js:61:21
    at EventBus.js:614:13
    at Zr._invokeListener (EventBus.js:457:19)
    at Zr._invokeListeners (EventBus.js:431:24)
    at Zr.fire (EventBus.js:379:24)
    at ChangeSupport.js:46:14
    at EventBus.js:614:13
    at Zr._invokeListener (EventBus.js:457:19)
    at Zr._invokeListeners (EventBus.js:431:24)
    at Zr.fire (EventBus.js:379:24)
    at ChangeSupport.js:54:16
    at Array.forEach (<anonymous>)
    at ChangeSupport.js:53:14
    at EventBus.js:614:13
    at Zr._invokeListener (EventBus.js:457:19)
    at Zr._invokeListeners (EventBus.js:431:24)
    at Zr.fire (EventBus.js:379:24)
    at Kv._popAction (CommandStack.js:503:20)
    at Kv.execute (CommandStack.js:187:8)
    at Kg.moveElements (Modeling.js:243:22)
    at Move.js:177:14
    at EventBus.js:614:13
    at Zr._invokeListener (EventBus.js:457:19)
    at Zr._invokeListeners (EventBus.js:431:24)
    at Zr.fire (EventBus.js:379:24)
    at s (Dragging.js:187:21)
    at l (Dragging.js:283:21)
    at HTMLDocument.u (Dragging.js:332:5)
    at HTMLDocument.o (helpers.ts:98:17)
```

### Expected Behavior

No errors

### Environment

 - Browser: Chrome Version 128

**Comment by abdul99ahad** [comment]
Hi, we have two potential approaches to address the issue where a text annotation is placed above a flow element label:

**Ignore the connection label:** This approach avoids breaking anything but may raise some UX concerns.

**Gracefully adjust the connection label:** This works well for simple connections, but it introduces inconsistencies when dealing with more complex cases.

Ignoring the connection label is simpler but may impact the user experience, while handling the adjustment offers better UX in basic scenarios but struggles with more complex connections.

**Comment by abdul99ahad** [comment]
Handling label positions for complex connections involves a more intricate process. At the moment, we’re opting to ignore the connection label when one is present, as we currently don’t support label adjustment for connections.
