### ISSUE TITLE
Publish initial documentation to docs.bpmn.io

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#329]
* [x] add a publish script to our release repositories
* [ ] regularily publish the stuff via CI

**Comment by nikku** [comment]
The release script seems to require a too new version of NodeJS. In our CI NodeJS v0.10.0 fails with:

```
15:56:33 Removing some stuff..
15:56:33 
15:56:33 .../jobs/bpmn-io-stage-docs/workspace/bpmn-io-release/docs.bpmn.io/docs.bpmn.io/index.js:76
15:56:33 execSync('rm -rf docs/content/*');
15:56:33 ^
15:56:33 TypeError: undefined is not a function
15:56:33     at Object.<anonymous> (.../jobs/bpmn-io-stage-docs/workspace/bpmn-io-release/docs.bpmn.io/docs.bpmn.io/index.js:76:1)
15:56:33     at Module._compile (module.js:456:26)
15:56:33     at Object.Module._extensions..js (module.js:474:10)
15:56:33     at Module.load (module.js:356:32)
15:56:33     at Function.Module._load (module.js:312:12)
15:56:33     at Function.Module.runMain (module.js:497:10)
15:56:33     at startup (node.js:119:16)
15:56:33     at node.js:935:3
```

**Comment by nikku** [comment]
Anything else that needs to be done here?

**Comment by ricardomatias** [comment]
Nope.
