### ISSUE TITLE
getAttribute of undefined (IE 11)

### ISSUE THREAD

**Issue by santosguilherme** [bpmn-io/bpmn-js#621]
An error is displayed in IE 11 browser console, occurs when switching between the hand tool and the selection tool (changing these tools via keyboard shortcut also the error occurs).

In the demo website this error also occurs.

I'm using this version of bpmn-js: 0.15.2.

Error:

`TypeError: Não é possível obter a propriedade 'getAttribute' de referência indefinida ou nula
   at Anonymous function (http://demo.bpmn.io/bpmn/app.min.js:15:244)
   at i (http://demo.bpmn.io/bpmn/app.min.js:19:18090)
   at o (http://demo.bpmn.io/bpmn/app.min.js:10:26158)
   at i.prototype._invokeListener (http://demo.bpmn.io/bpmn/app.min.js:10:27644)
   at i.prototype._invokeListeners (http://demo.bpmn.io/bpmn/app.min.js:10:27550)
   at i.prototype.fire (http://demo.bpmn.io/bpmn/app.min.js:10:27220)
   at m (http://demo.bpmn.io/bpmn/app.min.js:12:4002)
   at _ (http://demo.bpmn.io/bpmn/app.min.js:12:5004)
   at C (http://demo.bpmn.io/bpmn/app.min.js:12:5564)
   at i.prototype.activateHand (http://demo.bpmn.io/bpmn/app.min.js:12:12277)`

I'm available for more information.

Thank you

**Comment by pedesen** [comment]
I can reproduce this with IE11 and bpmn-js0.17.3 using the select tool.

**Comment by pedesen** [comment]
Fixed via https://github.com/bpmn-io/bpmn-js/commit/db0ce65aa403a53979733d5773bfa01fb0d00d68.

**Comment by santosguilherme** [comment]
Thanks @pedesen
